In [1]:
# Initial imports.
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# Loading data
file_path = Path("../Final_Project/All_Fighters_aligned.csv")
df_fighters = pd.read_csv(file_path)
df_fighters.head()

,Results,R_avg_KD,R_avg_opp_KD,R_avg_SIG_STR_pct,R_avg_opp_SIG_STR_pct,R_avg_TD_pct,R_avg_opp_TD_pct,R_avg_SUB_ATT,R_avg_opp_SUB_ATT,R_avg_REV,...,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,1,1.000000,0.000000,0.500000,0.460000,0.000000,0.00000,0.000000,0.00000,0.00000,...,0,0,1,0,0,170.18,177.80,135.0,31.0,27.0
1,1,1.031250,0.062500,0.576875,0.381250,0.406250,0.11625,0.250000,1.18750,0.37500,...,1,0,3,0,0,182.88,187.96,185.0,32.0,28.0
2,1,0.546875,0.187500,0.538906,0.598594,0.000000,0.31250,0.000000,0.25000,0.00000,...,0,1,3,0,0,187.96,190.50,264.0,32.0,28.0
3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,160.02,160.02,115.0,28.0,25.0
4,0,0.000000,0.000977,0.403076,0.554961,0.511719,0.62875,0.231445,0.03125,0.03125,...,0,1,2,2,0,167.64,172.72,135.0,29.0,43.0

In [3]:
df_fighters = df_fighters.dropna()
df_fighters

,Results,R_avg_KD,R_avg_opp_KD,R_avg_SIG_STR_pct,R_avg_opp_SIG_STR_pct,R_avg_TD_pct,R_avg_opp_TD_pct,R_avg_SUB_ATT,R_avg_opp_SUB_ATT,R_avg_REV,...,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,1,1.000000,0.000000,0.500000,0.460000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0,0,1,0,0,170.18,177.80,135.0,31.0,27.0
1,1,1.031250,0.062500,0.576875,0.381250,0.406250,0.116250,0.250000,1.18750,0.37500,...,1,0,3,0,0,182.88,187.96,185.0,32.0,28.0
2,1,0.546875,0.187500,0.538906,0.598594,0.000000,0.312500,0.000000,0.25000,0.00000,...,0,1,3,0,0,187.96,190.50,264.0,32.0,28.0
4,0,0.000000,0.000977,0.403076,0.554961,0.511719,0.628750,0.231445,0.03125,0.03125,...,0,1,2,2,0,167.64,172.72,135.0,29.0,43.0
5,0,0.312500,0.015625,0.565156,0.343594,0.337031,0.048906,0.039062,0.00000,0.00000,...,1,2,2,2,0,182.88,190.50,155.0,27.0,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5929,1,0.000000,0.000000,0.680000,0.420000,1.000000,0.000000,0.000000,0.00000,0.00000,...,0,0,0,1,0,185.42,190.50,205.0,30.0,31.0
5947,1,0.000000,0.000000,0.523750,0.465000,0.718750,0.000000,1.062500,0.00000,0.00000,...,0,0,1,2,0,185.42,182.88,205.0,28.0,32.0
5957,0,0.000000,0.000000,0.547500,0.750000,0.437500,0.000000,1.125000,0.00000,0.00000,...,0,0,1,2,0,185.42,182.88,205.0,28.0,31.0
5967,1,0.000000,0.000000,0.695000,0.500000,0.875000,0.000000,0.250000,0.00000,0.00000,...,0,0,1,1,0,185.42,182.88,205.0,37.0,31.0
5979,0,0.000000,0.000000,0.940000,0.750000,0.750000,0.000000,0.500000,0.00000,0.00000,...,0,0,1,1,0,185.42,182.88,205.0,28.0,31.0

In [4]:
# Define the features set.
X = df_fighters.copy()
X = X.drop("Results", axis=1)
X.head()

,R_avg_KD,R_avg_opp_KD,R_avg_SIG_STR_pct,R_avg_opp_SIG_STR_pct,R_avg_TD_pct,R_avg_opp_TD_pct,R_avg_SUB_ATT,R_avg_opp_SUB_ATT,R_avg_REV,R_avg_opp_REV,...,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,1.000000,0.000000,0.500000,0.460000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00,...,0,0,1,0,0,170.18,177.80,135.0,31.0,27.0
1,1.031250,0.062500,0.576875,0.381250,0.406250,0.116250,0.250000,1.18750,0.37500,0.25,...,1,0,3,0,0,182.88,187.96,185.0,32.0,28.0
2,0.546875,0.187500,0.538906,0.598594,0.000000,0.312500,0.000000,0.25000,0.00000,0.00,...,0,1,3,0,0,187.96,190.50,264.0,32.0,28.0
4,0.000000,0.000977,0.403076,0.554961,0.511719,0.628750,0.231445,0.03125,0.03125,0.50,...,0,1,2,2,0,167.64,172.72,135.0,29.0,43.0
5,0.312500,0.015625,0.565156,0.343594,0.337031,0.048906,0.039062,0.00000,0.00000,0.50,...,1,2,2,2,0,182.88,190.50,155.0,27.0,41.0

In [5]:
# Define the target set.
y = df_fighters["Results"].values
y[:5]

array([1, 1, 1, 0, 0], dtype=int64)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [7]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3757, 68)
(1253, 68)
(3757,)
(1253,)

In [8]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=1)

In [10]:
# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

In [11]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)
predictions

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [12]:
# Calculating the confusion matrix.
conmat = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
conmat_df = pd.DataFrame(
    conmat, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

conmat_df

          Predicted 0  Predicted 1
Actual 0           78          368
Actual 1           79          728

In [13]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.6432561851556265

In [15]:
# Displaying results
print("Confusion Matrix")
display(conmat_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           78          368
Actual 1           79          728

Accuracy Score : 0.6432561851556265
Classification Report
              precision    recall  f1-score   support

           0       0.50      0.17      0.26       446
           1       0.66      0.90      0.77       807

    accuracy                           0.64      1253
   macro avg       0.58      0.54      0.51      1253
weighted avg       0.60      0.64      0.58      1253