In [28]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
file_path = Path('../Machine Learning/popular_features_fighters.csv')
fighter_df = pd.read_csv(file_path)
fighter_df.head(10)

,Results,diff_CTRL_time(seconds),diff_GROUND_att,diff_GROUND_landed,diff_TD_landed,diff_SUB_ATT,diff_TD_pct,avg_KD
0,1,-49.000000,0.000000,0.000000,-49.000000,49.000000,-98.000000,147.000000
1,1,21.468750,11.437500,8.718750,12.750000,-4.031250,16.781250,-20.812500
2,1,-7.328125,-4.000000,-3.406250,-3.921875,0.515625,-4.437500,4.953125
3,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0,-168.867188,-2.131836,-1.531250,-167.335938,165.804688,-333.140625,498.945312
5,0,-134.515625,3.210938,4.515625,-139.031250,143.546875,-282.578125,426.125000
6,0,-78.937500,0.875000,1.000000,-79.937500,80.937500,-160.875000,241.812500
7,1,154.296829,18.328171,14.659668,139.637161,-124.977493,264.614654,-389.592148
8,1,-1.937500,5.562500,5.187500,-7.125000,12.312500,-19.437500,31.750000
9,1,56.500000,0.500000,-1.000000,57.500000,-58.500000,116.000000,-174.500000

In [30]:
fighter_df = fighter_df.dropna()
fighter_df.head(10)

,Results,diff_CTRL_time(seconds),diff_GROUND_att,diff_GROUND_landed,diff_TD_landed,diff_SUB_ATT,diff_TD_pct,avg_KD
0,1,-49.000000,0.000000,0.000000,-49.000000,49.000000,-98.000000,147.000000
1,1,21.468750,11.437500,8.718750,12.750000,-4.031250,16.781250,-20.812500
2,1,-7.328125,-4.000000,-3.406250,-3.921875,0.515625,-4.437500,4.953125
3,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0,-168.867188,-2.131836,-1.531250,-167.335938,165.804688,-333.140625,498.945312
5,0,-134.515625,3.210938,4.515625,-139.031250,143.546875,-282.578125,426.125000
6,0,-78.937500,0.875000,1.000000,-79.937500,80.937500,-160.875000,241.812500
7,1,154.296829,18.328171,14.659668,139.637161,-124.977493,264.614654,-389.592148
8,1,-1.937500,5.562500,5.187500,-7.125000,12.312500,-19.437500,31.750000
9,1,56.500000,0.500000,-1.000000,57.500000,-58.500000,116.000000,-174.500000

In [31]:
y = fighter_df["Results"]
X = fighter_df.drop(columns="Results")

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(9013, 7)

In [33]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=2000,
                                random_state=1)

In [34]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=1)

In [35]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            1       0
2            0       0
3            0       0
4            0       0
5            0       1
6            0       0
7            0       1
8            0       1
9            0       1
10           0       0
11           0       0
12           0       0
13           1       0
14           0       1
15           0       0
16           0       0
17           0       0
18           1       0
19           0       1

In [36]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.5417637271214643

In [37]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[1164  365]
 [1012  464]]

In [38]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.53      0.76      0.63      1529
           1       0.56      0.31      0.40      1476

    accuracy                           0.54      3005
   macro avg       0.55      0.54      0.52      3005
weighted avg       0.55      0.54      0.52      3005