In [25]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
file_path = Path('../final_pro/a_faa_stance.csv')
fighter_df = pd.read_csv(file_path)
fighter_df.head(10)

,Results,avg_KD,avg_opp_KD,avg_SIG_STR_pct,avg_opp_SIG_STR_pct,avg_TD_pct,avg_opp_TD_pct,avg_SUB_ATT,avg_opp_SUB_ATT,avg_REV,...,win_by_Decision_Split,win_by_Decision_Unanimous,win_by_KO/TKO,win_by_Submission,win_by_TKO_Doctor_Stoppage,Stance,Height,Reach,Weight,Age
0,1,1.000000,0.000000,0.500000,0.460000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0,0,1,0,0,1.0,170.18,177.80,135.0,27.0
1,1,1.031250,0.062500,0.576875,0.381250,0.406250,0.116250,0.250000,1.18750,0.37500,...,1,0,3,0,0,1.0,182.88,187.96,185.0,28.0
2,1,0.546875,0.187500,0.538906,0.598594,0.000000,0.312500,0.000000,0.25000,0.00000,...,0,1,3,0,0,2.0,187.96,190.50,264.0,28.0
3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,3.0,160.02,160.02,115.0,25.0
4,0,0.000000,0.000977,0.403076,0.554961,0.511719,0.628750,0.231445,0.03125,0.03125,...,0,1,2,2,0,1.0,167.64,172.72,135.0,43.0
5,0,0.312500,0.015625,0.565156,0.343594,0.337031,0.048906,0.039062,0.00000,0.00000,...,1,2,2,2,0,1.0,182.88,190.50,155.0,41.0
6,0,0.625000,0.000000,0.493125,0.430000,0.000000,0.687500,0.000000,0.25000,0.25000,...,0,1,3,0,0,1.0,182.88,180.34,170.0,31.0
7,1,0.024551,0.220703,0.515636,0.445974,0.355824,0.000000,0.000092,0.00000,0.00000,...,0,4,7,1,0,2.0,185.42,195.58,185.0,37.0
8,1,0.750000,0.000000,0.615000,0.474375,0.668750,0.386875,0.062500,1.25000,0.62500,...,0,2,0,1,0,2.0,177.80,190.50,135.0,28.0
9,1,0.000000,0.250000,0.420000,0.417500,0.362500,0.225000,0.000000,0.25000,0.00000,...,0,0,0,0,0,NaN,182.88,NaN,185.0,31.0

In [27]:
fighter_df = fighter_df.dropna()
fighter_df.head(10)

,Results,avg_KD,avg_opp_KD,avg_SIG_STR_pct,avg_opp_SIG_STR_pct,avg_TD_pct,avg_opp_TD_pct,avg_SUB_ATT,avg_opp_SUB_ATT,avg_REV,...,win_by_Decision_Split,win_by_Decision_Unanimous,win_by_KO/TKO,win_by_Submission,win_by_TKO_Doctor_Stoppage,Stance,Height,Reach,Weight,Age
0,1,1.000000,0.000000,0.500000,0.460000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0,0,1,0,0,1.0,170.18,177.80,135.0,27.0
1,1,1.031250,0.062500,0.576875,0.381250,0.406250,0.116250,0.250000,1.18750,0.375000,...,1,0,3,0,0,1.0,182.88,187.96,185.0,28.0
2,1,0.546875,0.187500,0.538906,0.598594,0.000000,0.312500,0.000000,0.25000,0.000000,...,0,1,3,0,0,2.0,187.96,190.50,264.0,28.0
4,0,0.000000,0.000977,0.403076,0.554961,0.511719,0.628750,0.231445,0.03125,0.031250,...,0,1,2,2,0,1.0,167.64,172.72,135.0,43.0
5,0,0.312500,0.015625,0.565156,0.343594,0.337031,0.048906,0.039062,0.00000,0.000000,...,1,2,2,2,0,1.0,182.88,190.50,155.0,41.0
6,0,0.625000,0.000000,0.493125,0.430000,0.000000,0.687500,0.000000,0.25000,0.250000,...,0,1,3,0,0,1.0,182.88,180.34,170.0,31.0
7,1,0.024551,0.220703,0.515636,0.445974,0.355824,0.000000,0.000092,0.00000,0.000000,...,0,4,7,1,0,2.0,185.42,195.58,185.0,37.0
8,1,0.750000,0.000000,0.615000,0.474375,0.668750,0.386875,0.062500,1.25000,0.625000,...,0,2,0,1,0,2.0,177.80,190.50,135.0,28.0
10,0,0.000000,0.000000,0.530000,0.490000,0.280000,0.000000,0.000000,0.00000,0.000000,...,0,0,0,0,0,2.0,165.10,172.72,125.0,27.0
11,0,0.000000,0.281250,0.561562,0.573320,0.392773,0.070312,0.777344,0.06250,1.015625,...,0,0,1,5,0,1.0,190.50,195.58,205.0,34.0

In [28]:
y = fighter_df["Results"]
X = fighter_df.drop(columns="Results")

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(6918, 68)

In [30]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=5000,
                                random_state=1)

In [31]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=5000, random_state=1)

In [32]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       1
1            0       0
2            1       1
3            0       0
4            1       1
5            0       0
6            1       1
7            1       1
8            0       1
9            1       1
10           1       0
11           1       1
12           1       1
13           1       1
14           1       1
15           1       1
16           1       0
17           0       1
18           1       1
19           1       0

In [33]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.5617685305591678

In [34]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[534 572]
 [439 762]]

In [35]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.55      0.48      0.51      1106
           1       0.57      0.63      0.60      1201

    accuracy                           0.56      2307
   macro avg       0.56      0.56      0.56      2307
weighted avg       0.56      0.56      0.56      2307